# Use the official Node.js image as the base image
FROM node
# Set the working directory in the container
WORKDIR /app
# Copy the package.json and package-lock.json files to the container
COPY package*.json ./
# Install the backend dependencies
RUN npm install
# Copy the rest of the backend source code to the container
COPY . .
# Expose the port that your NestJS server listens on (e.g., 5000)
EXPOSE 5000
# Start the NestJS application
CMD ["npm", "start"]
